// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdNI5s-jScRErXhSx58kdFUKZoW6SX4BQ',
    appId: '1:1042884195663:web:61848eaca102147696c13a',
    messagingSenderId: '1042884195663',
    projectId: 'zoom-clone-a2c04',
    authDomain: 'zoom-clone-a2c04.firebaseapp.com',
    storageBucket: 'zoom-clone-a2c04.appspot.com',
    measurementId: 'G-X2L9HKKDS6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrW6gwEzFxzBHh6B09kW_Px3ZR66gY7K8',
    appId: '1:1042884195663:android:2602b0d1288d2b4196c13a',
    messagingSenderId: '1042884195663',
    projectId: 'zoom-clone-a2c04',
    storageBucket: 'zoom-clone-a2c04.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfv7RONsXNZDqTg1l9efjhcCmMMCDvLIQ',
    appId: '1:1042884195663:ios:bd9de290c71028e896c13a',
    messagingSenderId: '1042884195663',
    projectId: 'zoom-clone-a2c04',
    storageBucket: 'zoom-clone-a2c04.appspot.com',
    androidClientId: '1042884195663-3n1ksbc6m0tvlll7o2bnot0hcovqjbea.apps.googleusercontent.com',
    iosClientId: '1042884195663-1pn9d8pme531riadtn3q2jn24j3h5gjr.apps.googleusercontent.com',
    iosBundleId: 'com.example.zoomClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfv7RONsXNZDqTg1l9efjhcCmMMCDvLIQ',
    appId: '1:1042884195663:ios:bd9de290c71028e896c13a',
    messagingSenderId: '1042884195663',
    projectId: 'zoom-clone-a2c04',
    storageBucket: 'zoom-clone-a2c04.appspot.com',
    androidClientId: '1042884195663-3n1ksbc6m0tvlll7o2bnot0hcovqjbea.apps.googleusercontent.com',
    iosClientId: '1042884195663-1pn9d8pme531riadtn3q2jn24j3h5gjr.apps.googleusercontent.com',
    iosBundleId: 'com.example.zoomClone',
  );
}
